# --- START OF FILE employees.py ---

users = {
    "sugunazugo@gmail.com": {
        "password": "zugo@123",
        "name": "SUGUNA SUNDARAJOTHI",
        "email": "sugunasundarajothi@gmail.com",
        "photo": "suguna.jpeg", # Assuming suguna.jpeg exists in static
        "joining_date": "21-08-2025",
        "employee_number": "ZPL001",
        "phone": "8344987196",
        "parent_phone": "9487504851",
        "dob": "18/06/2000",
        "gender": "Female",
        "job_role": "AI & ML DEVELOPER",
        "native": "The Nilgiris",
        "address": "19/3 olimada , uppatty post , pandalur taluk ,The Nilgiris - 643241",
        "aadhar": "2756 1817 0839",
        "total_leave": 0,  # Will be calculated/managed elsewhere
        "total_working": 0 # Will be calculated
    },
    "zugopvtnetwork@gmail.com": { # HR Account
        "password": "zugo@123",
        "name": "Zugo Pvt HR",
        "email": "zugopvtnetwork@gmail.com",
        "photo": "profile.jpg",
        "joining_date": "01-01-2020",
        "employee_number": "HR001",
        "address": "Bangalore",
        "phone": "9000000000",
        "parent_phone": "N/A",
        "dob": "01-01-1980",
        "gender": "N/A",
        "job_role": "HR Manager",
        "native": "Bangalore",
        "aadhar": "XXXXXXXXXXXX",
        "total_leave": 0,
        "total_working": 0
    },
    "nandhakumarzugopvt@gmail.com": {
        "password": "nandha123",
        "name": "NANDHAKUMAR T",
        "email": "nandhakumar1152@gmail.com",
        "photo": "nandhu.jpg", 
        "joining_date": "30/08/2025",
        "employee_number": "ZPL010",
        "phone": "9360202144",
        "parent_phone": "7010110289",
        "dob": "15/03/2001",
        "gender": "Male",
        "job_role": "Video editor",
        "native": "Namakkal",
        "address": "3/324,murugankoil, salemroad,Namakkal - 637001",
        "aadhar": "2028 9976 5232",
        "total_leave": 0,
        "total_working": 0
    },
     "nanthuzugopvt@gmail.com": {
        "password": "nanthu@123",
        "name": "NANTHAKUMAR K S",
        "email": "ksnandhakumarcgm@gmail.com",
        "photo": "Nanthu_ks.jpeg", 
        "joining_date": "21.08.2025",
        "employee_number": "ZPL002",
        "phone": "6379546463",
        "parent_phone": "8925685424",
        "dob": "24.10.2003",
        "gender": "Male",
        "job_role": "Web Developer",
        "native": "Thiruvannamalai",
        "address": "74, MGR Nagar, Rajaji Street, Chengam, Thiruvannamalai",
        "aadhar": "6162 1005 8657",
        "total_leave": 0,
        "total_working": 0
    },
    "sindhuzugopvt@gmail.com": {
        "password": "sindhu@123",
        "name": "SINDHU G",
        "email": "sindhugnanasekaran609@gmail.com",
        "photo": "sindhu.jpeg", 
        "joining_date": "21.08.2025",
        "employee_number": "ZPL003",
        "phone":"7305488701",
        "parent_phone": "9944922396",
        "dob": "03.05.2002",
        "gender": "Female",
        "job_role":" HR manager",
        "native": "Tiruppur",
        "address": "05, Thanner panthal colony Tiruppur 641 652",
        "aadhar": "6154 6184 1827",
        "total_leave": 0,
        "total_working": 0
    },
    "pavithrazugopvt@gmail.com": {
        "password": "pavithra@123",
        "name": "PAVITHIRA",
        "email": " pavithirarb@gmail.com ",
        "photo": "pavithra.jpeg", 
        "joining_date": "21.08.25",
        "employee_number": "ZPL009",
        "phone": "9790441487",
        "parent_phone": "81485 41136",
        "dob": "02.08.2003",
        "gender": "female ",
        "job_role": "marketing and sales ",
        "native": "Pondicherry ",
        "address": "no.75 , krishna nagar main road lawspet , Pondicherry-605008",
        "aadhar": "7582 0730 2031",
        "total_leave": 0,
        "total_working": 0
    },
    # "akshayparoononzugopvt@gmail.com": {
    #     "password": "akshay@123",
    #     "name": "Akshaya Paroonon ",
    #     "email": "raiovlogs23@gmail.com",
    #     "photo": "akshay.jpg", 
    #     "joining_date": "21.08.25",
    #     "employee_number": "ZPL007",
    #     "phone": "7034772492",
    #     "parent_phone": "9072466185",
    #     "dob": "23.09.2000",
    #     "gender": "male",
    #     "job_role": "cinematographer ",
    #     "native": "kerala",
    #     "address": "amruthalayam,thalachangadu,naduvanadu 670702",
    #     "aadhar": "6805 9772 6581",
    #     "total_leave": 0,
    #     "total_working": 0
    # },
    "arunzugopvt@gmail.com": {
        "password": "Arun@123",
        "name": "ARUN K",
        "email": "arunkumaradhik7@gmail.com",
        "photo": "arun.png", 
        "joining_date": "21/08/2025",
        "employee_number": "ZPL008",
        "phone": "7339100395",
        "parent_phone": "7550182906",
        "dob": "10/10/2001",
        "gender": "Male",
        "job_role": "Creative Designer",
        "native": "Chennai",
        "address": "6/9 kandhan kollai, Sevvappet, Thiruvallur ",
        "aadhar": "2248 2601 3305",
        "total_leave": 0,
        "total_working": 0
    },
     "bharathzugopvt@gmail.com": {
        "password": "bharath@123",
        "name": "BHARATH RAJ .M",
        "email": "bharath24112001@gmail.com",
        "photo": "bharath.JPG", 
        "joining_date": "21.08.2025",
        "employee_number": "ZPL005",
        "phone": "8667841036",
        "parent_phone": "9487560529",
        "dob": "24.11.2001",
        "gender": "male",
        "job_role": "sales and marketing ",
        "native": "Tirupur",
        "address": "202/1b kuttivannan 1 at street samundipuram Tirupur 641603",
        "aadhar": "6072 9860 6570",
        "total_leave": 0,
        "total_working": 0
    },
    "someshzugopvt@gmail.com": {
        "password": "somesh@123",
        "name": "SOMESH KANNA",
        "email": "somsaf0411@gmail.com",
        "photo": "somesh.jpg", 
        "joining_date": "21.08.2015",
        "employee_number": "ZPL004",
        "phone": "9345784828",
        "parent_phone": "6374931974",
        "dob": "03.06.2005",
        "gender": "male ",
        "job_role": "social media manager",
        "native": "karaikudi",
        "address": "bharathi street,  kallal",
        "aadhar": "3655 3245 0652",
        "total_leave": 0,
        "total_working": 0
    },
    "kavinazugopvt@gmail.com": {
        "password": "kavina123",
        "name": "KAVINA S",
        "email": "kavinanavab@gmail.com",
        "photo": "kavina.jpeg", 
        "joining_date": "29.09.2025",
        "employee_number": "ZPL011",
        "phone": "9789295388",
        "parent_phone": "9345147407",
        "dob": "12.01.2001",
        "gender": "Female",
        "job_role": "Marketing",
        "native": "Erode",
        "address": "8/4705, Mahaanatham Garden, Amman Nagar, Pooluvapatti, Tiruppur - 641602",
        "aadhar": "9184 6293 8703",
        "total_leave": 0,
        "total_working": 0
    },
    "sornakumarzugopvt@gmail.com": {
        "password": "Sorna@123",
        "name": "SORNAKUMAR",
        "email": "sornakumarzugopvt@gmail.com",
        "photo": "sornakumar.JPG", 
        "joining_date": "23/09/2025",
        "employee_number": "ZPL010",
        "phone": "8148789949",
        "parent_phone": "8190950457",
        "dob": "01/04/1984",
        "gender": "male",
        "job_role": "sales and marketing",
        "native": "Tirupur",
        "address": "246A , thiruneelakandar veethi 2 nd Street ,Thirumuruganpoondi,Tirupur_641652",
        "aadhar": "7874 0307 1611",
        "total_leave": 0,
        "total_working": 0
    }
}